export { default as Arrow1 } from './Arrow1';
export { default as Arrow2 } from './Arrow2';
export { default as Arrow3 } from './Arrow3';
export { default as Arrow4 } from './Arrow4';
export { default as FooterLogo } from './FooterLogo';
export { default as KakaoTalkButtonDefault } from './KakaoTalkButtonDefault';
export { default as Logo } from './Logo';
export { default as Support1 } from './Support1';
export { default as Support2 } from './Support2';
